# Generated by Django 3.2.8 on 2022-08-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_depts_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('yrlevel', models.IntegerField()),
                ('yrgraduate', models.IntegerField()),
                ('studentnum', models.CharField(max_length=100)),
                ('dept', models.CharField(max_length=100)),
                ('contactperson', models.CharField(max_length=100)),
                ('pdate', models.CharField(max_length=100)),
                ('ptime', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=100)),
            ],
        ),
    ]
