# Generated by Django 3.2.8 on 2022-08-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_appointmentform'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentform',
            name='status',
            field=models.CharField(default='status', max_length=100),
        ),
    ]
