# Generated by Django 3.2.8 on 2022-08-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_appointmentform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentform',
            name='notes',
            field=models.CharField(default='notes', max_length=100),
        ),
        migrations.AddField(
            model_name='appointmentform',
            name='username',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
