# Generated by Django 3.2.8 on 2022-08-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220817_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentform',
            name='notes',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointmentform',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointmentform',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
