# Generated by Django 3.2.8 on 2022-08-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20220817_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentform',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
