# Generated by Django 3.2.8 on 2022-08-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20220817_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentform',
            name='yrgraduate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointmentform',
            name='yrlevel',
            field=models.IntegerField(),
        ),
    ]
