# Generated by Django 3.2.8 on 2022-08-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20220817_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='cssform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('transaction', models.CharField(max_length=100)),
                ('signature', models.CharField(max_length=100)),
                ('timeliness', models.IntegerField()),
                ('completeness', models.IntegerField()),
                ('professionalism', models.IntegerField()),
                ('courteousness', models.IntegerField()),
                ('overall', models.IntegerField()),
                ('feedback', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
