# Generated by Django 3.2.8 on 2022-08-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_depts_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDFSave', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
