# Generated by Django 4.1.3 on 2022-11-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_appointmentform_yrgraduate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentform',
            name='contactperson_email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
