# Generated by Django 4.1.3 on 2022-11-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_appointmentform_contactperson_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='depts',
            name='position',
            field=models.CharField(default='', max_length=200, verbose_name='position'),
            preserve_default=False,
        ),
    ]
