# Generated by Django 4.1.3 on 2022-11-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_depts_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depts',
            name='position',
        ),
    ]
