# Generated by Django 4.1.3 on 2022-11-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_remove_depts_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='depts',
            name='position',
            field=models.CharField(choices=[('Head', 'Head'), ('Faculty', 'Faculty')], default='', max_length=200, verbose_name='position'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depts',
            name='department',
            field=models.CharField(choices=[('Head', 'Head'), ('Faculty', 'Faculty')], max_length=200, verbose_name='department'),
        ),
    ]
