# Generated by Django 4.1.3 on 2022-11-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_depts_position_alter_depts_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depts',
            name='department',
            field=models.CharField(choices=[('OAA', 'Office of Academic Affairs'), ('DIT', 'Department of Information Technology'), ('DLA', 'Department of Liberal Arts'), ('OCL', 'Office of Campus Library'), ('DED', 'Department of Education'), ('DMS', 'Department of Mathematics and Science'), ('DOE', 'Department of Engineering'), ('OSA', 'Office of Student Affairs'), ('UITC', 'University Information Technology Center'), ('DPE', 'Department of Physical Education'), ('SD', 'Security Department'), ('RE', 'Research & Extension')], max_length=200, verbose_name='department'),
        ),
    ]
