# Generated by Django 4.1.3 on 2022-12-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_depts_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentform',
            name='date_submit',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
