# Generated by Django 4.1.3 on 2022-12-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_appointmentform_date_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentform',
            name='sd_status',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
